# Generated by Django 3.2.12 on 2022-03-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lessonview'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avata',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/'),
        ),
    ]
