# Generated by Django 3.2.12 on 2022-03-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_user_avata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avata',
            new_name='avatar',
        ),
    ]
